server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_movie?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    dbcp2:
      # 获取链接时是否验证
      test-on-borrow: false
      # 空闲链接回收的时间间隔
      time-between-eviction-runs-millis: 300000
      # 空闲链接的有效时间
      min-evictable-idle-time-millis: 1800000
      initial-size: 5
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1532760526@qq.com #QQ邮箱
    password: rlqdsvfmyzipfhcg    #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: aaa #可以任意
    properties.mail.display.sendname: bbb #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true #开启SSL
    default-encoding: utf-8


#Mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:mybatis/mapper/*.xml

web:
  # 文件上传路径
  upload-path: D:/ticketweb_data/
  movie-post-path: moviepost/
  avatar-path: advatar/
  default-post: default.png
  default-avatar: default.jpg

logging:
  level:
    com.dogeyes.zyf.mapper: debug
